### ISSUE TITLE
BiocLite tries to update old packages in root directory

### ISSUE THREAD

**Issue by ghost** [Bioconductor/Bioconductor#2]
Many thanks for your work on the package.

Every time I try to install a package through biocLite, the library ask if I want to update some old packages (Matrix, memoise, survival). Even though I do, and the packages are saved in the my user directory (it's a multi-user server), when I use biocLite again it again tries to update those three packages.

It would seem that biocLite first looks at the root directory and does not take into that those packages are already installed in the user directory.

I presume this is something that could be easily fixed?

**Comment by LiNk-NY** [comment]
This issue was moved to Bioconductor/BiocInstaller#1
